# Generated by Django 4.1.3 on 2022-12-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_id', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=100)),
                ('assign_date', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=200)),
                ('employee_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
    ]
