# Generated by Django 4.1.3 on 2022-12-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigndetails',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='assigndetails',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='assigndetails',
            name='assign_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assigndetails',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
