# Generated by Django 4.1.3 on 2022-12-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField()),
                ('department_name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'assetmanager.department',
            },
        ),
    ]
