# Generated by Django 4.1.3 on 2022-12-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_showdepartment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='showdepartment',
            table=None,
        ),
    ]
