# Generated by Django 4.1.3 on 2022-12-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_showdepartment_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowDepartment',
        ),
    ]
