# Generated by Django 4.1.3 on 2022-12-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_delete_showdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.BigIntegerField()),
                ('employee_name', models.CharField(max_length=100)),
                ('department_id', models.IntegerField()),
                ('designation_id', models.IntegerField()),
                ('unit_id', models.IntegerField()),
                ('contact', models.CharField(max_length=100)),
                ('employee_mail', models.CharField(max_length=100)),
                ('office_location_id', models.IntegerField()),
                ('employee_status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='ViewDep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
    ]
