# Generated by Django 4.1.3 on 2022-12-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('manufacture_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('vendor_id', models.IntegerField()),
                ('warranty_till', models.DateField()),
                ('serial_IMEI', models.CharField(max_length=100)),
                ('specification', models.CharField(max_length=500)),
                ('invoice_no', models.CharField(max_length=200)),
                ('purchase_date', models.DateField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
