# Generated by Django 4.1.3 on 2022-12-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('manufacturer_name', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=100)),
                ('has_warrenty', models.CharField(max_length=100)),
                ('warrenty_till', models.CharField(max_length=100)),
                ('serial_IMEI', models.CharField(max_length=100)),
                ('specification', models.CharField(max_length=100)),
                ('invoice_no', models.CharField(max_length=100)),
                ('purchase_date', models.CharField(max_length=100)),
            ],
        ),
    ]
