# Generated by Django 4.1.3 on 2022-12-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewStoock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('stock_in_date', models.CharField(max_length=100)),
                ('available_stock', models.CharField(max_length=100)),
            ],
        ),
    ]
