# Generated by Django 4.1.3 on 2022-12-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('department_name', models.CharField(max_length=100)),
                ('designation_name', models.CharField(max_length=100)),
                ('unit_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('emp_mail', models.CharField(max_length=100)),
                ('office_loc', models.CharField(max_length=100)),
                ('emp_status', models.CharField(max_length=100)),
            ],
        ),
    ]
