# Generated by Django 4.1.3 on 2022-12-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('assign_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'assign_asset',
            },
        ),
    ]
