# Generated by Django 4.1.3 on 2022-12-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('role_id', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
